:PROPERTIES:
#+TODO: TODO DOING | DONE
:END:
* Hardware
* Software
** Interfaces
*** TODO UART interface
    See [[http://en.wikipedia.org/wiki/Universal_asynchronous_receiver/transmitter][Wikipedia]]
** Sensors
*** LSM303 - Accelerometer and Magnetometer
    [[https://www.sparkfun.com/datasheets/Sensors/Magneto/LSM303%2520Datasheet.pdf][Datasheet]]
**** TODO Check magnetometer axes ordering
     There are at least two versions of this sensor, and the registers are in different orders
     One has X,Y,Z; the other has X,Z,Y
**** DOING Measure 3D magnetization vector
**** DOING Accelerometer interface
*** L3GD20 - Gyroscope
    Also measures temperature for some reason
*** BMP180 - Barometer
    Measures pressure and temperature. also calculates altitude
*** BH1750FVI - Light sensor
    Measures ambient light
** GPS
   [[http://www.adafruit.com/product/746][Adafruit Ultimate GPS]]
** Comms
   [[https://www.sparkfun.com/products/9411][XTend module]]?
** Logging
   Need to decide on a logging format
*** JSON
    How about something like this:
    {
      "Timestamp":"2015/05/25 17:15:41.301530"
      "Type":"data",
      "Source":"BMP180"
      "Value":{
        "Temperature":0
        "Pressure":0
        "Altitude":0
      }
    }
    This allows the program parsing the data to use a single struct to parse anything:
    struct {
      Timestamp string
      Type      string
      Source    string
      Value     byte[]
    }
    And then you can parse Value if and only if it's the type of data you're interested in.
    So it'll be easy to write a program to, for example, make a graph of pressure vs altitude, even when you have all sorts of data in one file.
* Other
  If this file becomes unmanageable, we'll consider [[http://orgmode.org/worg/org-contrib/gsoc2012/student-projects/org-sync/][org-sync]]
** TODO Legal issues
   Send NOTAM to nearby airports in advance of launch,
   but under 115 cu ft ballon capacity there is little
   regulation. With a parachute, payload weight is a
   non-issue provided the parachute is designed to
   slow the payload descent to < 3.5 m/s.

   This [[http://www.arawr.ca/?page=legal][page]] has a good example and more information.
* Local Variables
  Emacs will complain about this.
  Feel free to get rid of them - maybe put this in your .emacs config.
# Local Variables:
# eval: (setq org-todo-keyword-faces '(("TODO" . "red") ("DOING" . "yellow") ("DONE" . "green")));
# End:
